# This code was generated by ChatGPT in Dec 2024.

#############
############# CLEAR WORKSPACE
#############

rm(list=ls())
set.seed(42)
data(iris)

#############
############# TRADITIONAL BINNING APPROACH
#############

# Divide the continuous variable "Sepal.Length" into 4 quantile bins
iris$SepalLengthBin <- cut(iris$Sepal.Length, 
                          breaks = quantile(iris$Sepal.Length, 
                                            probs = seq(0, 1, 0.25)), 
                          include.lowest = TRUE)

# Inspect the resulting strata
table(iris$SepalLengthBin)

#############
############# CLUSTERING APPROACH
#############

# Perform k-means clustering on two continuous variables
iris_cluster <- kmeans(iris[, c("Sepal.Length", "Petal.Length")], centers = 4)

# Assign clusters as strata
iris$Cluster <- as.factor(iris_cluster$cluster)

# Inspect the resulting strata
table(iris$Cluster)

#############
############# VISUALIZE THE CLUSTERING RESULTS
#############

# Visualize the clusters
library(ggplot2)
ggplot(iris, aes(x = Sepal.Length, y = Petal.Length, color = Cluster)) +
  geom_point() +
  labs(title = "Strata Defined by k-means Clustering") +
  theme_minimal()